plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.15'
}

version = '0.1.0'

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'posit'
    className = 'com.posit.nextflow.workbench.WorkbenchPlugin'
    extensionPoints = [
        'com.posit.nextflow.workbench.WorkbenchExecutor'
    ]
}
